const presetLibrary = {
  pizzaBalls: {
    name: "Pizza",
    type: "sized-unit",
    unitLabel: "balls",
    customLabel: "Flour per ball",
    defaultQuantity: 2,
    defaultSize: "medium",
    sizes: {
      small: { label: "Small", flour: 120 },
      medium: { label: "Medium", flour: 150 },
      large: { label: "Large", flour: 180 },
      custom: { label: "Custom", flour: 150 },
    },
    hydration: 65,
    salt: 2.5,
    yeast: 0.2,
    oil: 0,
    sugar: 0,
  },

  bagels: {
    name: "Bagels",
    type: "fixed-unit",
    unitLabel: "bagels",
    defaultQuantity: 10,
    flourPerUnit: 70,
    hydration: 58,
    salt: 2.5,
    yeast: 0.8,
    oil: 0,
    sugar: 4,
  },

  focaccia: {
    name: "Focaccia",
    type: "sized-batch",
    unitLabel: "trays",
    customLabel: "Flour per tray",
    defaultQuantity: 1,
    defaultSize: "medium",
    sizes: {
      small: { label: "Small", flour: 300 },
      medium: { label: "Medium", flour: 500 },
      large: { label: "Large", flour: 750 },
      custom: { label: "Custom", flour: 500 },
    },
    hydration: 80,
    salt: 2.5,
    yeast: 0.5,
    oil: 5,
    sugar: 0,
  },

   naan: {

    name: "Naan",
    type: "fixed-unit",
    unitLabel: "naan",
    defaultQuantity: 4,
    flourPerUnit: 60,
    hydration: 53,
    salt: 2.5,
    yeast: 1,
    oil: 0,
    sugar: 0,
    yogurt: 26.5,

  },
  chapati: {
  name: "Chapati",
  type: "fixed-unit",
  unitLabel: "chapati",
  defaultQuantity: 8,
  flourPerUnit: 20,
  hydration: 60,
  salt: 2.5,
  yeast: 0,
  oil: 0,
  sugar: 0,
},

sourdough: {
  name: "Sourdough",
  type: "sized-unit",
  unitLabel: "loaves",
  customLabel: "Flour per loaf",
  defaultQuantity: 1,
  defaultSize: "medium",
  sizes: {
    small: { label: "Small", flour: 300 },
    medium: { label: "Medium", flour: 500 },
    large: { label: "Large", flour: 700 },
    custom: { label: "Custom", flour: 500 },
  },
  hydration: 70,
  salt: 3,
  starter: 20,
  yeast: 0,
  oil: 0,
  sugar: 0,

}

};